### ISSUE TITLE
post一次 会收到两条消息

### ISSUE THREAD

**Issue by dangmeng** [JeremyLiao/LiveEventBus#111]
LiveEventBus.get(LiveDataEventKey.USER_MUTED, String.class).post(s)
Observer会收到两条 这个消息。。。 请问做让它收到一条就可以了，
、利用消息跳转activity 也会重复跳转

**Comment by cjecky** [comment]
我也发现这个问题了，请问解决了吗@dangmeng

**Comment by dangmeng** [comment]
> 我也发现这个问题了，请问解决了吗@dangmeng

我升级了最新版本。。好像解决了吧  你试试
