### ISSUE TITLE
Activity包含Fragment嵌套的时候发送消息的问题

### ISSUE THREAD

**Issue by hloong** [JeremyLiao/LiveEventBus#112]
一个Activity包含ABC三个Fragment，AFragment包含DEF三个子Fragment
用Activity定时循环发送消息，AFragment的三个子fragment可以收到，然后切换到BFragment的时候，再切回A后消息就收不到了，试过sticky也不行，是否应用场景不适合用这个库？

**Comment by xionger0520** [comment]
@hloong 我猜你没有在onResume中订阅消息 这样一切换出去就解除订阅了自然接收不到消息

**Comment by hloong** [comment]
> @hloong 我猜你没有在onResume中订阅消息 这样一切换出去就解除订阅了自然接收不到消息

有这方面原因，我后面切换成永久订阅，并在销毁的时候手动取消订阅了
