### ISSUE TITLE
没找到DEMO源码啊

### ISSUE THREAD

**Issue by Skqing** [JeremyLiao/LiveEventBus#13]
没找到DEMO源码啊，能发一下DEMO源码吗？

**Comment by JeremyLiao** [comment]
https://github.com/JeremyLiao/LiveEventBus/blob/master/live-event-bus/liveeventbus/src/main/java/com/jeremyliao/liveeventbus/LiveEventBusDemo.java

**Comment by Skqing** [comment]
多谢
