### ISSUE TITLE
作者大大有没有考虑过使用flow替代liveData

### ISSUE THREAD

**Issue by ld2006203** [JeremyLiao/LiveEventBus#140]
目前项目中用到了很多LiveData，发的多丢的多，而且由于LiveData Post也是在主线程中，所以还是有一定性能损耗的，且livedata不支持背压，作者大大有没有考虑过使用flow替代Livedata

**Comment by JeremyLiao** [comment]
貌似有一个基于flow的实现了：https://tech.bytedance.net/articles/6986469059034349598

**Comment by ld2006203** [comment]
大佬这是你们内网的吧，好像无法访问啊

**Comment by JeremyLiao** [comment]
> 大佬这是你们内网的吧，好像无法访问啊

sorry，没注意：）

**Comment by JeremyLiao** [comment]
https://juejin.cn/post/6985093305470025764
https://github.com/biubiuqiu0/flow-event-bus

**Comment by ld2006203** [comment]
谢谢大佬
