### ISSUE TITLE
关于观察者进入非活跃状态期间的消息全部抛弃的功能

### ISSUE THREAD

**Issue by 985530812** [JeremyLiao/LiveEventBus#18]
处于某些原因我有一个自定义的观察者，在某些情况下我会将他设置为非活跃状态。
我希望在非活跃状态期间这个观察者不接收任何消息并且在恢复活跃的时候也不接收之前发送过的消息，只接收下一条新消息。
我在LiveEventBus-V2的基础上做了一些尝试，但是并没有达成目的，不知道可否指点一下思路。

**Comment by JeremyLiao** [comment]
> 处于某些原因我有一个自定义的观察者，在某些情况下我会将他设置为非活跃状态。
> 我希望在非活跃状态期间这个观察者不接收任何消息并且在恢复活跃的时候也不接收之前发送过的消息，只接收下一条新消息。
> 我在LiveEventBus-V2的基础上做了一些尝试，但是并没有达成目的，不知道可否指点一下思路。

我在v2上改了一下代码，ok了，关键点一个是把LiveEventBus.get().lifecycleObserverAlwaysActive(false);其二就是在activeStateChanged方法做一些判断，diff如下：

index b3a9560..152618b 100644
--- a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/LiveEventBusDemo.java
+++ b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/LiveEventBusDemo.java
@@ -228,7 +228,10 @@ public class LiveEventBusDemo extends AppCompatActivity {
     }
 
     public void sendMessageSetBefore() {
-        LiveEventBus.get().with(randomKey, String.class).setValue("msg set after");
+//        LiveEventBus.get().with(randomKey, String.class).setValue("msg set after");
+        LiveEventBus.get()
+                .with(LiveEventBusDemo.KEY_TEST_ACTIVE_LEVEL)
+                .postValue("Send Msg To Observer ReStarted");
     }
 
     public void testObserverActiveLevel() {
diff --git a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
index 6f9bdd9..4e58150 100644
--- a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
+++ b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
@@ -18,6 +18,7 @@ public class ObserverActiveLevelActivity extends AppCompatActivity {
         binding = DataBindingUtil.setContentView(this, R.layout.activity_observer_active_level_demo);
         binding.setLifecycleOwner(this);
         binding.setHandler(this);
+        LiveEventBus.get().lifecycleObserverAlwaysActive(false);
     }
 
     @Override
diff --git a/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java b/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
index 94a6711..9f4dc46 100644
--- a/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
+++ b/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
@@ -423,13 +423,15 @@ public abstract class LiveEvent<T> {
             mActive = newActive;
             boolean wasInactive = LiveEvent.this.mActiveCount == 0;
             LiveEvent.this.mActiveCount += mActive ? 1 : -1;
+            boolean justActive = false;
             if (wasInactive && mActive) {
+                justActive = true;
                 onActive();
             }
             if (LiveEvent.this.mActiveCount == 0 && !mActive) {
                 onInactive();
             }
-            if (mActive) {
+            if (mActive && !justActive) {
                 dispatchingValue(this);
             }
         }

**Comment by 985530812** [comment]
> > 处于某些原因我有一个自定义的观察者，在某些情况下我会将他设置为非活跃状态。
> > 我希望在非活跃状态期间这个观察者不接收任何消息并且在恢复活跃的时候也不接收之前发送过的消息，只接收下一条新消息。
> > 我在LiveEventBus-V2的基础上做了一些尝试，但是并没有达成目的，不知道可否指点一下思路。
> 
> 我在v2上改了一下代码，ok了，关键点一个是把LiveEventBus.get().lifecycleObserverAlwaysActive(false);其二就是在activeStateChanged方法做一些判断，diff如下：
> 
> index b3a9560..152618b 100644
> --- a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/LiveEventBusDemo.java
> +++ b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/LiveEventBusDemo.java
> @@ -228,7 +228,10 @@ public class LiveEventBusDemo extends AppCompatActivity {
> }
> 
> ```
>  public void sendMessageSetBefore() {
> ```
> * ```
>      LiveEventBus.get().with(randomKey, String.class).setValue("msg set after");
>   ```
> 
> +// LiveEventBus.get().with(randomKey, String.class).setValue("msg set after");
> 
> * ```
>      LiveEventBus.get()
>   ```
> * ```
>              .with(LiveEventBusDemo.KEY_TEST_ACTIVE_LEVEL)
>   ```
> * ```
>              .postValue("Send Msg To Observer ReStarted");
>   ```
>   }
>   public void testObserverActiveLevel() {
>   diff --git a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
>   index 6f9bdd9..4e58150 100644
>   --- a/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
>   +++ b/branchs/live-event-bus-v2/app-v2/src/main/java/com/jeremyliao/lebapp/ObserverActiveLevelActivity.java
>   @@ -18,6 +18,7 @@ public class ObserverActiveLevelActivity extends AppCompatActivity {
>   binding = DataBindingUtil.setContentView(this, R.layout.activity_observer_active_level_demo);
>   binding.setLifecycleOwner(this);
>   binding.setHandler(this);
> * ```
>      LiveEventBus.get().lifecycleObserverAlwaysActive(false);
>   ```
>   }
>   @override
>   diff --git a/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java b/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
>   index 94a6711..9f4dc46 100644
>   --- a/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
>   +++ b/branchs/live-event-bus-v2/liveeventbus-v2/src/main/java/com/jeremyliao/liveeventbus/liveevent/LiveEvent.java
>   @@ -423,13 +423,15 @@ public abstract class LiveEvent {
>   mActive = newActive;
>   boolean wasInactive = LiveEvent.this.mActiveCount == 0;
>   LiveEvent.this.mActiveCount += mActive ? 1 : -1;
> * ```
>          boolean justActive = false;
>          if (wasInactive && mActive) {
>   ```
> * ```
>              justActive = true;
>              onActive();
>          }
>          if (LiveEvent.this.mActiveCount == 0 && !mActive) {
>              onInactive();
>          }
>   ```
> 
> * ```
>          if (mActive) {
>   ```
> 
> * ```
>          if (mActive && !justActive) {
>              dispatchingValue(this);
>          }
>      }
>   ```

我使用了该方法进行了尝试 但是有一个如下问题：
当我将活跃状态指定为RESUME时一切照预期运行 但是如果活跃状态指定为STARTED之后 观察者回归至CREATE再返回STARTED时依旧收到了上次发出的消息
    
    我的测试方法是：在第一个activity建立一个自定义观察者，并初始化状态为STARTED；
    在点击按钮之后跳转至第二个activity并将该观察者指定为CREATE状态；
    点击activity2的按钮发送消息后回到activity1并将观察者状态返回STARTED，
    此时观察者依旧接收到了activity2中发出的消息

**Comment by 985530812** [comment]
> 你是直接去覆写了observerActiveLevel函数吗？这个值并不建议在执行过程中去改动，否则会比较混乱，observerActiveLevel这个函数的含义是指定观察者在哪些状态下认为是活跃的，LiveData里面有个内部类LifecycleBoundObserver，有如下方法：
> @override
> boolean shouldBeActive() {
> return mOwner.getLifecycle().getCurrentState().isAtLeast(STARTED);
> }
> 说明了LiveData默认认为至少是STARTED的观察者才是active的，这些观察者才应该收到消息

是的 我将原先的

    protected Lifecycle.State observerActiveLevel() {
        return lifecycleObserverAlwaysActive ? Lifecycle.State.CREATED : Lifecycle.State.STARTED;
    }
           
中的返回值替换为了
         
    return lifecycleObserverAlwaysActive ? Lifecycle.State.CREATED : Lifecycle.State.RESUMED;
         
参照activity的生命周期，我认为RESUMED状态比STARTED状态更适合在我所需求的场景下表明活跃状态，所以我使用这个状态来替换了STARTED，并且当我没有替换使用原先的设定时就会出现我在先前描述过的问题

**Comment by 1079107009** [comment]
我看到过一篇文章https://tech.meituan.com/2018/07/26/android-livedatabus.html

**Comment by 985530812** [comment]
> 我看到过一篇文章https://tech.meituan.com/2018/07/26/android-livedatabus.html

哈哈 我就是看到这篇文章才找过来的
