### ISSUE TITLE
support sticky

### ISSUE THREAD

**Issue by wang9090980** [JeremyLiao/LiveEventBus#2]
hi: 支持sticky吗？

**Comment by JeremyLiao** [comment]
你指的是postDelay这种吗？现在是不支持的，现在支持setValue和postValue。如果要做postDelay的话需要在这set或者post的时候作delay

**Comment by ChaosOctopus** [comment]
他的意思是  像EventBus那种的粘性注册。

**Comment by JeremyLiao** [comment]
现在可以支持sticky了
