### ISSUE TITLE
类型转换存在隐患

### ISSUE THREAD

**Issue by qingjuyashi** [JeremyLiao/LiveEventBus#21]
您好，如果我提前注册一个接受Boolean的订阅者，然后在子线程发送一个String型消息，会直接报类型转换crash。
此类隐患建议避免

**Comment by qingjuyashi** [comment]
建议只开放Object类型的with方法：
public Observable<Object> with(String key) {
        if (!bus.containsKey(key)) {
            bus.put(key, new BusLiveData<>(key));
        }
        return bus.get(key);
    }
让用户在Observer中接收数据时候自己做强转判断

**Comment by JeremyLiao** [comment]
多谢指出这个问题，我想想有什么好的解决方式没

**Comment by JeremyLiao** [comment]
这个问题已经解决，如果发送消息的类型错误，会收不到消息，但是不会crash，请使用v1.2.2版本，commit参见：https://github.com/JeremyLiao/LiveEventBus/commit/3104064b2877b62f5236828ffa1530cbff60bc16
