### ISSUE TITLE
Viewmodel

### ISSUE THREAD

**Issue by liupeng826** [JeremyLiao/LiveEventBus#28]
这个liveeventbus是不是不需要配合viewmodel是用啊，任何类型model都可以吧。

**Comment by JeremyLiao** [comment]
只依赖livedata，同viewmodel无关

**Comment by liupeng826** [comment]
这个不能再ViewData里面使用，如何做到代码分层？大部分逻辑还是要等数据取回后处理，这样需要写在activity或者fragement中，以前使用EventBus，不依赖生命周期，可以在Presenter中处理这些逻辑，现在改成viewModel后大部分逻辑要移回activity或者fragement中了，能不能分享一下你们的项目架构？

**Comment by JeremyLiao** [comment]
LiveEventBus是纯粹的总线框架，与使用mvc、mvp或者mvvm构架没有关系。根据你的描述应该是使用基于databinding的mvvm模式吧。在这种模式下我还是喜欢在Activity中注册LiveEventBus，这样具有生命周期感知，在Activity中是持有viewmodel实例的，当总线的消息到来的时候，再通过viewmodel去通知视图更新

**Comment by liupeng826** [comment]
是的，我用的是MVVM，我是在application中配置的，在activity创建更新UI的观察者，Activity中也是持有viewmodel， 但是消息来的时候怎么能在viewmodel中捕获数据呢？难道是从activiy传到viewMode，然后viewmodel再去通知视图更新？这样不是变复杂了？

**Comment by JeremyLiao** [comment]
是的，我们现在就是这样做的，在Activity中注册观察者，然后消息来的时候调用viewmodel更新视图，其实这样职责划分很明确，activity中封装所有逻辑，viewmodel只负责视图更新

**Comment by liupeng826** [comment]
这和以前MVP正好相反，P层负责取回数据，传给Activity, activity只负责更新UI

**Comment by liupeng826** [comment]
有些奇怪，明明是ViewModel调用repository取数据，结果要在Activity中监听再传回ViewModel

**Comment by JeremyLiao** [comment]
> 有些奇怪，明明是ViewModel调用repository取数据，结果要在Activity中监听再传回ViewModel

嗯，因为LiveEventBus只是个消息总线，并不关注你使用的是mvp还是mvvm
