### ISSUE TITLE
混淆了并不能用啊

### ISSUE THREAD

**Issue by yushilong** [JeremyLiao/LiveEventBus#37]
-dontwarn com.jeremyliao.liveeventbus.**
-keep class com.jeremyliao.liveeventbus.LiveEventBus { *; }
-keep class android.arch.lifecycle.ExternalLiveData { *; }
-dontwarn android.arch.lifecycle.LiveData
-keep class android.arch.lifecycle.LiveData { *; }
-keep class android.arch.lifecycle.LifecycleRegistry { *; }
-keep class android.arch.core.internal.SafeIterableMap { *; }

**Comment by yushilong** [comment]
哦 我知道了 我用的androidx
规则改下就可以了：
-dontwarn com.jeremyliao.liveeventbus.**
-keep class com.jeremyliao.liveeventbus.LiveEventBus { *; }
-keep class androidx.lifecycle.ExternalLiveData { *; }
-dontwarn androidx.lifecycle.LiveData
-keep class androidx.lifecycle.LiveData { *; }
-keep class androidx.lifecycle.LifecycleRegistry { *; }
-keep class androidx.arch.core.internal.SafeIterableMap { *; }

**Comment by JeremyLiao** [comment]
> 哦 我知道了 我用的androidx
> 规则改下就可以了：
> -dontwarn com.jeremyliao.liveeventbus.**
> -keep class com.jeremyliao.liveeventbus.LiveEventBus { *; }
> -keep class androidx.lifecycle.ExternalLiveData { *; }
> -dontwarn androidx.lifecycle.LiveData
> -keep class androidx.lifecycle.LiveData { *; }
> -keep class androidx.lifecycle.LifecycleRegistry { *; }
> -keep class androidx.arch.core.internal.SafeIterableMap { *; }

嗯，androidx混淆上稍微有点区别，后面会把这块补上，thx
