### ISSUE TITLE
gradle5以后，没有android.arch.lifecycle.Observer

### ISSUE THREAD

**Issue by Rocketer2018** [JeremyLiao/LiveEventBus#40]
我用的是Gradle5.1.1的。构建之后。没有android.arch.lifecycle.Observer，这个库就用不了。。。忘up主早日升级gradle5。我也多看看源码，看看能否直接引用源码，然后自己改改。

**Comment by JeremyLiao** [comment]
我理解跟gradle版本应该没有关系，check一下你的dependency呢，是否有implementation "android.arch.lifecycle:livedata:1.1.1"

**Comment by Rocketer2018** [comment]
哦好的，gradle4.7的时候，没有去引用android.arch.lifecycle:livedata:1.1.1，便可以运行。所以我没注意项目中是否有android.arch.lifecycle:livedata:1.1.1。而升级到5.1.1之后发现没有Observer了。而且所引用的android.arch.lifecycle的包也有变化，所以我认为是gradle5.1.1所引用的包的问题。
。稍等我看一下。项目中是否有android.arch.lifecycle:livedata:1.1.1

**Comment by Rocketer2018** [comment]
implementation "android.arch.lifecycle:livedata:1.1.1"，引用这个包之后就可以了。
这是gradle一个误导我的地方。up主此库没有问题。之前用的是gradle 4.7构建，不用手动引用 "android.arch.lifecycle:livedata:1.1.1"。现在升级5.1.1之后，引用的lifecycle的库变了。手动引用一下之后就好了。

**Comment by Rocketer2018** [comment]
如果有和我一样刚升5的。并且手动implementation "android.arch.lifecycle:livedata:1.1.1"的。升了之后先把build文件夹删掉，或者clean一下。再重新编译。否则报类重复，observer已经引用过。的错误。
