### ISSUE TITLE
重复监听问题

### ISSUE THREAD

**Issue by liupeng826** [JeremyLiao/LiveEventBus#48]
两个ActivityA B 中都监听同一个key，用的是普通observer,A和B分别都会更新数据库，key是用来监听更新结果的。从A跳到B，在B中更新数据库后，再从B返回A的时候会触发A里面的监听.

Androidx 1.4.0版本

**Comment by liupeng826** [comment]
两个Activity中都监听同一个key，用的是普通observer,A和B分别都会更新数据库，key是用来监听更新结果的。从A跳到B，在B中更新数据库后，再从B返回A的时候会触发A里面的监听.

**Comment by JeremyLiao** [comment]
这个情况，lifecycleObserverAlwaysActive应该设置的是false吧，因为两个activity都是同一个key，更新之后B会收到消息，但是这个时候A不会收到消息，因为A不是active的，但是当回到A的时候，A变成了active，这个时候A就会收到消息

**Comment by liupeng826** [comment]
这个还真设置成false了，不起作用

**Comment by JeremyLiao** [comment]
因为你使用的是同一个key，所以更新数据库之后A和B都会收到消息，但是A会在变成active的时候再收到这个消息，如果想更新的时候A立刻收到消息，需要把lifecycleObserverAlwaysActive设置成true

**Comment by liupeng826** [comment]
在B里面已经收到消息了，我不想在A变成active的时候收到这个消息，lifecycleObserverAlwaysActive我设置成了false，但是A还是收到了消息

**Comment by JeremyLiao** [comment]
A监听了那个key，是一定会收到消息的，lifecycleObserverAlwaysActive只是决定是立刻收到消息还是返回的时候收到消息

**Comment by liupeng826** [comment]
哦，这样啊，那如何让A不能接收到消息呢？同一个Key。
在B里面能销毁那个消息吗？

**Comment by JeremyLiao** [comment]
我理解你既然监听了，也发生了更新，不是应该收到消息吗？

**Comment by liupeng826** [comment]
不是啊，前后两个页面AB都处理同一个逻辑，处理成功后处理不同的UI逻辑。如果接受两次会出问题的

**Comment by JeremyLiao** [comment]
这种场景感觉不像观察者了，而是消费者模式？

**Comment by liupeng826** [comment]
如果我在B页面用observeForever订阅，然后在页面销毁时removeObserver，可以解决这个问题吗？
目前我用observe，然后在页面销毁时removeObserver，不起作用。

**Comment by JeremyLiao** [comment]
不行，这个只是解除当前的订阅关系，而不会影响其他人的订阅

**Comment by liupeng826** [comment]
明白了，多谢，我再想想别的办法
