### ISSUE TITLE
请问大佬的类头注释怎么写的

### ISSUE THREAD

**Issue by GreenhairTurtle** [JeremyLiao/LiveEventBus#51]
没错，就是那个很骚气的LiveEventBus
一个个打出来的吗？
还是有啥便捷方法，我也想玩点花的

**Comment by JeremyLiao** [comment]
http://patorjk.com/software/taag/#p=display&f=Avatar&t=LiveEventBus

**Comment by GreenhairTurtle** [comment]
谢谢大佬
