### ISSUE TITLE
建议跨进程消息支持配置前台广播队列

### ISSUE THREAD

**Issue by lancewoo** [JeremyLiao/LiveEventBus#52]
对于跨进程通信既然是用广播实现的，有没有考虑到广播队列的效率问题？Android系统中默认使用的广播消息队列是后台广播消息，如果使用的应用非常多的话，不排除会出现阻塞问题，那么效率就是个问题了。另一方面，前台广播队列使用频率非常低，如果偶尔用一下对一些比较关键的消息的及时送达还是很有必要的。因此建议增加一个接口可以配置使用前台广播队列，要不然，我可能得自己改造一下了~~ 
@JeremyLiao

**Comment by JeremyLiao** [comment]
好的建议，我想一想，另外，也欢迎提pr。：）

**Comment by JeremyLiao** [comment]
> 对于跨进程通信既然是用广播实现的，有没有考虑到广播队列的效率问题？Android系统中默认使用的广播消息队列是后台广播消息，如果使用的应用非常多的话，不排除会出现阻塞问题，那么效率就是个问题了。另一方面，前台广播队列使用频率非常低，如果偶尔用一下对一些比较关键的消息的及时送达还是很有必要的。因此建议增加一个接口可以配置使用前台广播队列，要不然，我可能得自己改造一下了~~
> @JeremyLiao

新版已支持，版本‘1.4.4’，调用broadcast(value, true)

**Comment by lancewoo** [comment]
> 
> 
> > 对于跨进程通信既然是用广播实现的，有没有考虑到广播队列的效率问题？Android系统中默认使用的广播消息队列是后台广播消息，如果使用的应用非常多的话，不排除会出现阻塞问题，那么效率就是个问题了。另一方面，前台广播队列使用频率非常低，如果偶尔用一下对一些比较关键的消息的及时送达还是很有必要的。因此建议增加一个接口可以配置使用前台广播队列，要不然，我可能得自己改造一下了~~
> > @JeremyLiao
> 
> 新版已支持，版本‘1.4.4’，调用broadcast(value, true)

赞一个，这速度杠杠滴！ @JeremyLiao
