### ISSUE TITLE
有取消事件传递的功能吗

### ISSUE THREAD

**Issue by chsmy** [JeremyLiao/LiveEventBus#56]
你好有没有类似EventBus中的取消事件传递的功能：EventBus.getDefault().cancelEventDelivery(event) ;

现在A页面跳到B页面，B页面跳到C页面 ，A和B都订阅了同一个事件，C发送事件 。但是有时候只想B接收不想A接收。现在是发送的时候加个type值处理的。

**Comment by JeremyLiao** [comment]
没有在发送端对消息的cancel，只有接收端自己去unregister，你这种场景可以在消息中包含一个target，然后在接收消息的时候根据这个target判断要不要处理这个消息
