### ISSUE TITLE
LiveDataBus中的bus这个map对象数据是否会一直持有，很多的时候是不是一种内存泄露？

### ISSUE THREAD

**Issue by yrickwong** [JeremyLiao/LiveEventBus#7]

**Comment by JeremyLiao** [comment]
这个map对象是一直持有的，据我所知，所有的bus类组件，如rxbus，eventbus都会一直持有，但是区别于缓存类组件，bus类组件一般持有的都是String，Integer等小对象，不会持有Bitmap等会占用大量内存的对象，所以不用太担心这个问题

**Comment by SoarY** [comment]
map集合里面也存了很多LiveData对象，也就是说项目了注册了多少，里面就存多少，没移除操作，这样是否友好，多了以后会不会影响其内存。

**Comment by JeremyLiao** [comment]
谢谢你的建议，以后会考虑添加把没有订阅者的observable定期清理掉的功能

**Comment by GreenhairTurtle** [comment]
能否这样，在BusMutableLiveData内重写onInactive方法
```java
protected void onInactive() {
      super.onInactive();
      if (!hasObservers()) {
        LiveEventBus .bus.remove(eventKey);
      }
    }
```
当然，需要为BusMutableLiveData添加构造方法
```java
public BusMutableLiveData(String eventKey){
     this.eventKey = eventKey;
}
```

**Comment by JeremyLiao** [comment]
嗯，我也是这样想的，在取消订阅或者类似onInactive的时机去检查当前Observer上面是否hasObservers，然后把这个Observer remove掉。这是个很好的思路，谢谢

**Comment by JeremyLiao** [comment]
> 能否这样，在BusMutableLiveData内重写onInactive方法
> 
> ```java
> protected void onInactive() {
>       super.onInactive();
>       if (!hasObservers()) {
>         LiveEventBus .bus.remove(eventKey);
>       }
>     }
> ```
> 
> 当然，需要为BusMutableLiveData添加构造方法
> 
> ```java
> public BusMutableLiveData(String eventKey){
>      this.eventKey = eventKey;
> }
> ```

这种方式确实不错，我再想想有没有什么问题，赞一个

**Comment by GreenhairTurtle** [comment]
这个方法刚刚验证了一下，是有问题的
onInactive回调时一般都仍然会有一个Observer，翻看源码发现
```java
@Override
        public void onStateChanged(LifecycleOwner source, Lifecycle.Event event) {
            if (mOwner.getLifecycle().getCurrentState() == DESTROYED) {
                removeObserver(mObserver);
                return;
            }
            activeStateChanged(shouldBeActive());
        }
```
在生命周期变化后，会回调onStateChanged方法，这里如果不为destroy，调用activeStateChanged方法
```java
void activeStateChanged(boolean newActive) {
            if (newActive == mActive) {
                return;
            }
            // immediately set active state, so we'd never dispatch anything to inactive
            // owner
            mActive = newActive;
            boolean wasInactive = LiveData.this.mActiveCount == 0;
            LiveData.this.mActiveCount += mActive ? 1 : -1;
            if (wasInactive && mActive) {
                onActive();
            }
            if (LiveData.this.mActiveCount == 0 && !mActive) {
                onInactive();
            }
            if (mActive) {
                dispatchingValue(this);
            }
        }
```
在activeStateChanged方法中 只有原先的mActiviCount=0（即1变为0）且mActive为true时才回调onInactive
然而，activity在destroy之前会走onPause，此时就会走上面流程，并回调onInactive，所以这里调用hasObservers返回true

不好意思，之前的方案是错误的

不过应该有方案解决，我看看

**Comment by GreenhairTurtle** [comment]
我刚试了下，重写removeObserver可以解决这个问题，虽然看起来好像简单粗暴哈哈
```java
 @Override
    public void removeObserver(@NonNull Observer<T> observer) {
      super.removeObserver(observer);
      if (!hasObservers()) {
        LiveEventBus.bus.remove(eventKey);
      }
    }
```

**Comment by JeremyLiao** [comment]
> 我刚试了下，重写removeObserver可以解决这个问题，虽然看起来好像简单粗暴哈哈
> 
> ```java
>  @Override
>     public void removeObserver(@NonNull Observer<T> observer) {
>       super.removeObserver(observer);
>       if (!hasObservers()) {
>         LiveEventBus.bus.remove(eventKey);
>       }
>     }
> ```

我看了LiveData的源码，确实这样是可行的。我准备使用你这种方法来弄。再次表示感谢：）

**Comment by JeremyLiao** [comment]
这个问题已解决，感谢提出这个问题的小伙伴以及@GreenhairTurtle的解决方案，具体参见commit：https://github.com/JeremyLiao/LiveEventBus/commit/9ae7b8c4cdec2cce654c3ad8aff2927b05401bb3
