### ISSUE TITLE
有没有什么办法能加入一个log处理的接口

### ISSUE THREAD

**Issue by kugarliyifan** [JeremyLiao/LiveEventBus#70]
有没有什么办法能加入一个log处理的接口,这样方便做日志记录之类的功能,每次发送或者接收到消息的时候,自动回调

**Comment by JeremyLiao** [comment]
暂时没有，会考虑这个需求

**Comment by JeremyLiao** [comment]
> 有没有什么办法能加入一个log处理的接口,这样方便做日志记录之类的功能,每次发送或者接收到消息的时候,自动回调

这个功能已经加上，版本1.5.1，commit：https://github.com/JeremyLiao/LiveEventBus/commit/3a82728f96237d6637e8cfcf70d7c42ed592943d

**Comment by kugarliyifan** [comment]
> > 有没有什么办法能加入一个log处理的接口,这样方便做日志记录之类的功能,每次发送或者接收到消息的时候,自动回调
> 
> 这个功能已经加上，版本1.5.1，commit：[3a82728](https://github.com/JeremyLiao/LiveEventBus/commit/3a82728f96237d6637e8cfcf70d7c42ed592943d)

大神好速度
