### ISSUE TITLE
接收后赋值再使用的问题

### ISSUE THREAD

**Issue by VainAnts** [JeremyLiao/LiveEventBus#89]
![QQ截图20191205145127](https://user-images.githubusercontent.com/9073302/70210969-f3a8f880-176e-11ea-8a9d-5d19b1d2b9a9.png)

您好，作者 这样写下面setText里面的mString为空，放在onChanged是可以成功的，但是需要做其他的操作感觉全部放在onChanged也不太妥当？请指点

**Comment by JeremyLiao** [comment]
我觉得String类型的mString可以使用LiveData<String>类型替代，这样在xml中绑定LiveData<String> mString，就不用setText了

**Comment by VainAnts** [comment]
感谢回复
