### ISSUE TITLE
isCallOnObserve 这个函数是干什么用的？

### ISSUE THREAD

**Issue by wzyzb** [JeremyLiao/LiveEventBus#9]

**Comment by JeremyLiao** [comment]
这个函数的作用是查找调用栈，看回调是不是由observeForever方法直接引起，如果是由observeForever直接引起则避免这次回调。另外还有一种实现请参考live-event 分支。更多原理介绍请参考此文：https://tech.meituan.com/Android_LiveDataBus.html
