### ISSUE TITLE
ViewPager2+Fragment中能否感知UserVisibleHint？

### ISSUE THREAD

**Issue by xtvj** [JeremyLiao/LiveEventBus#90]
我在Fragment中使用LiveEventBus.get(*,*).observe()方法监听数据来显示Dialog，但是ViewPager2滑动后不显示该Fragment时还是会收到数据变化，不知此框架是否有处理过Fragment在ViewPager里的情况，是我用的方式不对么？

**Comment by JeremyLiao** [comment]
fragment同SupportActivity不一样，不是一个LifecycleOwner，所以不会自动解除订阅，需要手动处理
![image](https://user-images.githubusercontent.com/23290617/70387021-fc056b80-19da-11ea-8de7-285dcb0c6e5a.png)

**Comment by xtvj** [comment]
soga，thank you
